### ISSUE TITLE
Doesn't hit 127.0.0.1:7650

### ISSUE THREAD

**Issue by orignal** [libre-net-society/i2pd-webui#2]
Run nc -l 7650 at first terminal.
Run python3 run.py at second.
Attempt to hit http://127.0.0.1:8082 produces following output at second terminal
## 127.0.0.1 - - [23/Dec/2015 11:06:26] "GET / HTTP/1.1" 200 -

Exception happened during processing of request from ('127.0.0.1', 40872)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "run.py", line 48, in do_GET
    resp_html(s)
  File "run.py", line 22, in resp_html
    s.wfile.write(f.read())
  File "/usr/lib/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
TypeError: 'str' does not support the buffer interface

No data came to the first terminal.

**Comment by orignal** [comment]
see it connected and JSON messages
